### PR TITLE
feature/#598_Style_frontend_test_user_switch_back_link

### PR DESCRIPTION
**Pull request by olatechpro**
- Style frontend test user switch back link #598

### CODE REVIEW

**Review by agapetry — CHANGES_REQUESTED** [review]
@olatechpro This is a lot better. I see the styling you developed was simply not being loaded on the front end. In testing with a random assortment of themes, I still found a few issues:

- Inheriting a theme-defined font color causes an inconsistent appearance (and sometimes poor contrast) on our white background (see Oceanly News Dark theme): 
image

- On some themes, our switch back box covers the theme's header bar without full opacity (see Planet Green): 
image

- On some themes, our switch back box is completely missing - apparently covered by the theme's higher-opacity header bar. (see Posterity, SKT Green themes): 
image

- The link underscore is hidden on most themes, but rendered with a few (see Twenty Twenty-One, Twenty Twenty-Two, Elyn): 
image

Note that we do have the link underscore displayed in Admin Dashboard:
image

If the decision is to also consistently render it on the front end, we should also forcibly specify the front end box's font. The "cutting off the tail" effect is much worse with some fonts.

**Comment by olatechpro** [comment]
@agapetry Since the purpose of the frontend switch back is for users without admin access or toolbar access.

I didn't see alternative to solve some of the issues you mentioned other than moving the switch back to footer just like most plugin do.

On different theme font and typography, that's my initial intention for leaving it a simple link just like most similar plugin since we may not be able to match every existing theme and we can't compare admin styling to frontend styling that load different styles that may overwrite appearance.

However, I've added !important to all styles attribute and that should do enough to force the styles.

If there's any alternative, I'm opened to suggestion.

**Comment by agapetry** [comment]
@olatechpro @stevejburge After trying a few different approaches to the theme header clash problem, I wised up and introduced a status caption and return link into the Admin Bar:

image

The footer notice designed by Ola remains, with minor styling adjustments:

image

image

This all seems pretty theme-tolerant, but I also introduced settings to disable either as needed. The Admin Bar modification does load enqueue jQuery on the front end when a user is tested.

image

**Review by agapetry — APPROVED** [review]
Approved with 4e2f977de1a8c565a4a04854346bc4db17dca6bd

**Pull request merged**
