### PR TITLE
Banner getting people to install Permissions with vendor library

### PR DESCRIPTION
**Pull request by htmgarcia**
#201

Alternative PR [to this](https://github.com/publishpress/PublishPress-Capabilities/pull/243) but handling banners through a vendor library.

### CODE REVIEW

**Comment by htmgarcia** [comment]
@agapetry @stevejburge documentation explaining how this library works: https://publishpress.github.io/docs/interface/sidebar-banner

**Comment by stevejburge** [comment]
@htmgarcia Awesome work

**Comment by agapetry** [comment]
@htmgarcia Are there also deliberate changes to Editor Features screen construction in this PR, or are those just issues in synchronizing to other PRs / development branch changes ?

**Comment by htmgarcia** [comment]
@agapetry this implementation doesn't affect other features. The whole process from this PR is documented [here](https://publishpress.github.io/docs/interface/sidebar-banner).

**Pull request merged**
