### PR TITLE
feature/#11_Redirect_on_login_and_logout

### PR DESCRIPTION
**Pull request by olatechpro**
- Redirect on login and logout #11

### CODE REVIEW

**Review by agapetry — COMMENTED** [review]
@stevejburge This raises a couple questions:

1) If the redirect option is ever maliciously modified (whether manually or by other code), this plugin will be implicated for applying that redirect.  How can we mitigate that without losing desired functionality?  Limit redirects to the site domain only?  Any other sanitization beyond what esc_url_raw() does?

2) If the user has multiple roles, this current implementation loops through those roles in an essentially random order, taking the first available redirect.  It seems there should be some intentional logic about which redirect gets priority if multiple are assigned.

**Comment by olatechpro** [comment]
@agapetry @stevejburge 
For the (1.) We didn't perform the redirect but instead, we provided the redirect URL and the url is redirected by WordPress using [wp_safe_redirect()](https://developer.wordpress.org/reference/functions/wp_safe_redirect/) which only redirect if it's not an external link and for the sanitation, according to [esc_url_raw](https://developer.wordpress.org/reference/functions/esc_url_raw/) documentation, it purpose is to performs [esc_url() for database or redirect usage but if there's another suggestion on other method, i'm open to recommendation.

For the number 2, i'm opened to suggestion.

**Comment by stevejburge** [comment]
@olatechpro This one is over my head. I'll wait for @agapetry's thoughts

**Comment by agapetry** [comment]
@olatechpro The wp_safe_redirect() safeguards will be sufficient. Let's just note a need for additional testing as we push this plugin farther into active filtering of user login behavior.

For the second issue, I suggest modifying the "Chosen JS" functionality to:

- display roles in the same order they are stored in the usermeta array
- make those items draggable for re-ordering
- save the roles to usermeta in the selected order

It seems that the original WordPress role is currently kept as the first element in the usermeta array (in spite of a different order displayed by the role selection UI).  The plan I propose would maintain and clarify the current behavior while allowing that primary role to be changed.

**Comment by olatechpro** [comment]
Noted @agapetry but i have clarification to make on this phrase... `For the second issue, I suggest modifying the "Chosen JS" functionality to:`

What part of the plugin are you referring to, i don't think we currently using Chosen library in the plugin?

Also, are you proposing making roles screen item draggable and update the new order?

**Comment by agapetry** [comment]
@olatechpro It's easy to forget about the multi-role selection UI on the Edit User screen:

https://github.com/publishpress/PublishPress-Capabilities/blob/fe34f25af0c17639d8f4c3d2ea59f27065eb292e/includes/admin-load.php#L168

image

**Comment by olatechpro** [comment]
@stevejburge haha, I’m sincerely didn’t know of this implementation till now. Now I understand, i’ll add issue on this and work on it on a separate branch.

**Pull request merged**
