### PR TITLE
Feature/2.4.0 to.1

### PR DESCRIPTION
**Pull request by olatechpro**

### CODE REVIEW

**Review by agapetry — COMMENTED** [review]
In Editor Features, it's a little disorienting to have Page listed first but default to Post:

image

**Review by agapetry — COMMENTED** [review]
@olatechpro I like the "Restricted" indicators; that's what will make this UI change work.

One problem, though: The very first time I saved an Editor Feature restriction, the "Restricted" indicator displayed without any styling:

image

Now it looks like I won't be able to recreate that for real without deleting a wp_options row.  This screen capture is simulated by editing the html class name.

**Comment by olatechpro** [comment]
1. Okay, i think the post type are sorted by name and that’s why Page came before Post which shows if there are post type that started with earlier alphabet, neither Page or Post will be on top.

So, putting that into consideration, should we set default tab as the first tab or what’s your suggestion?

2. I’m wondering if this could be css cache issue? Checking the restricted class element again, no reason for the class to disappear.


@agapetry

**Comment by olatechpro** [comment]
Okay, on the (1.) When i checked now, i think they are sorted by key. 

Should we make first CPT as default or simply add Post as first on the list @agapetry

**Comment by olatechpro** [comment]
Your proposal of 2 buttons make sense. I’ll make update on that @agapetry

**Comment by agapetry** [comment]
> > 2. I’m wondering if this could be css cache issue? Checking the restricted class element again, no reason for the class to disappear.
> 
> Maybe. I'll see if I can recreate it after clearing options.

@olatechpro I think you're right about this being a css cache symptom. The problem did not recur after clearing the stored options.

**Review by agapetry — APPROVED** [review]

**Pull request closed without merging**
