### PR TITLE
#16-Block access to frontend menu links

### PR DESCRIPTION
**Pull request by olatechpro**
As previously discussed, this features is not limited to roles alone but also extend option to set navigation menu permission for 'logged in users' or 'logged out users(Guest)' as a whole.

Apart from removing the restricted menu from the site nav bar, it also block access to the menu page if it's a post, page, cpt(any custom type post), categories, tags or any taxonomies.

Screenshot 2020-11-11 at 22 53 07
Screenshot 2020-11-11 at 22 54 37

### CODE REVIEW

**Comment by stevejburge** [comment]
Awesome, thanks @olatechpro

**Comment by agapetry** [comment]
@olatechpro Can you please submit this pull request to the "development-menus branch of Capabilities Pro instead.  Menu Restriction needs to be a Pro feature, so I moved your code into includes-pro:

https://github.com/publishpress/PublishPress-Capabilities-Pro/blob/development-menus/includes-pro/admin-load.php
https://github.com/publishpress/PublishPress-Capabilities-Pro/blob/development-menus/includes-pro/admin-menus.php
https://github.com/publishpress/PublishPress-Capabilities-Pro/blob/development-menus/includes-pro/functions-admin.php
https://github.com/publishpress/PublishPress-Capabilities-Pro/blob/development-menus/includes-pro/pro.css

So you'll need to merge your recent changes into those files.  I apologize for not clearly communicating this earlier.

**Comment by olatechpro** [comment]
Hi @agapetry , i just created a fix targetting the development-menus but seems i don't have write access and as a result, i can't make the PR.

**Comment by agapetry** [comment]
@olatechpro Can you let me know if you have the necessary access now?

**Comment by olatechpro** [comment]
No yet.....
no-write-access

**Comment by agapetry** [comment]
@olatechpro Have you cloned the Capabilities Pro repository and committed your changes there?

**Comment by olatechpro** [comment]
Screenshot 2020-12-07 at 17 09 03

**Comment by olatechpro** [comment]
No, i can't fork it since it's a private repository but i clone it to my system to make changes but can't commit without write access

**Comment by agapetry** [comment]
@olatechpro We're trying to determine why you need write access to Capabilities Pro, whereas read permission is sufficient for Capabilities.  This is nothing against you; I'm just trying to get the process right for outside contributors.

**Comment by agapetry** [comment]
@olatechpro So for the previous Capabilities PRs, you forked the repository first?

**Comment by olatechpro** [comment]
Yes, that's how i'm able to make a commit and then make a PR targetting origin branch.

Well, it's just a two files update. I'll add the two files as a branch here and you can simply copy that.

**Comment by olatechpro** [comment]
I just did. We can just close this and the new one after copying the 2 files

**Comment by agapetry** [comment]
Okay. I'm sorry about the inconvenience.  We'll try to get our process better defined.

**Comment by olatechpro** [comment]
`Okay. I'm sorry about the inconvenience. We'll try to get our process better defined.`

Smile, it's all good. The end goal is to get a result and that's the most important thing irrespective of the process

**Comment by agapetry** [comment]
@olatechpro I just chatted with Steve about these projects.  We want Menu restriction to be a Pro-only feature.  I had modified Capabilities [Free] to show a Restrict Menus link which leads to a promotional screen for Pro.  After you restore that code to your fork and take out any new menu restriction code, we can process a PR here (Capabilities [free]) for the "Roles" screen.

**Comment by olatechpro** [comment]
I didn't understand. I thought we didn't merge this branch yet?

**Comment by agapetry** [comment]
@olatechpro No, it's not merged yet. I just want to be sure that no Restrict Menus code comes into Capabilities [free] on PRs.

**Comment by olatechpro** [comment]
Oh, i just made a PR that remove admin menu codes from previously merged PR

**Comment by agapetry** [comment]
This code was manually merged into Capabilities Pro: https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/36

**Pull request closed without merging**
