### PR TITLE
- Hide features inside the "Edit Posts"

### PR DESCRIPTION
**Pull request by olatechpro**

### CODE REVIEW

**Comment by olatechpro** [comment]
As previously discussed, this PR enable admin to hide features in create/edit post area with tab option if classic editor is active so they can configure between the two editor but if classic editor is not active, the tab won't reflect.

Screenshot 2021-02-15 at 10 41 22

**Comment by stevejburge** [comment]
Awesome, thanks @olatechpro. We'll take a look.

**Comment by agapetry** [comment]
@olatechpro Thanks for developing this functionality.  We think it will become a major plugin feature.  I've reviewed this pull release and committed changes that fix a few issues and demonstrate some of our coding standards.  Please review each commit along with my commit comment to recognize some techniques and patterns we would like you to adopt moving forward.

You'll see that I also changed the terminology to "Editor Restrictions" and changed the option storage and UI to control these editor restrictions separately per post type.  For now, the free version will control standard editor elements for the Post and Page type, but filters allow us to expand that coverage in the Pro version.

I'll append some additional comments here for code that I committed without detailing:

Javascript redundancy:

- When writing jQuery handlers that need to consider differences in checked status or name attribute, set a local variable to store that difference.  Then you can use string concatenation and methods like toggleClass()
- Remember that jQuery methods can be chained.  As a result, there's no need to have two consecutive jQuery selector statements that are identical except for the final method.
- The jQuery .closest() and .find() methods can be useful in making element selection more concise and also more tolerant of changes to html structure.

https://github.com/publishpress/PublishPress-Capabilities/pull/120/commits/691656daa7f632e0fa65dc268e64d1828f700aa8

**Review by agapetry — COMMENTED** [review]
@olatechpro Thanks for developing this functionality. We think it will become a major plugin feature. I've reviewed this PR and committed fixes for a few issues along with some changes that  demonstrate coding standards we'd like you to follow. Please review each of these commits along with my commit comments.  The PR Conversation also includes some additional comments.

**Comment by olatechpro** [comment]
Noted @agapetry although by the time i worked on this feature and some others, the plugin code wasn't really following any coding standard like that and it was as it is and when i made the comment to @stevejburge , he said they're at the verge of refactoring the old code and as a result, i followed what i met there.

**Pull request merged**
