### PR TITLE
feature/#323_Stop_Free_and_Pro_from_being_enabled_together

### PR DESCRIPTION
**Pull request by olatechpro**
Feature/#323 stop free and pro from being enabled together

### CODE REVIEW

**Comment by agapetry** [comment]
@stevejburge Do you see a need to forcibly deactivate an existing Free plugin activation, or would it be enough to just respond to a new plugin activation request by converting a Pro + Free activation to Pro-only at that time?

Doing the latter would allow us to just filter the plugins option update - safer than calling the deactivate_plugins() function which is user-defined in pluggable.php.

**Comment by stevejburge** [comment]
@agapetry Sorry, I'm not sure I understand the difference between those two. Feel free to take what you think is the best route to stop the two being active together

**Comment by agapetry** [comment]
Okay. The difference is in applying that constraint at plugin activation time versus constantly monitoring for it.

**Comment by stevejburge** [comment]
Maybe constantly is best, just to avoid confusion?

**Comment by agapetry** [comment]
Do we also need to implement an admin notice so the user knows why their dual activation attempt fails? I suspect this is a case of "explain now or explain later."

**Comment by stevejburge** [comment]
lol, now we're getting into something we should standardize across plugins.

Yes, let's add an admin notice. We'll then add to our docs: https://publishpress.github.io/

**Comment by olatechpro** [comment]
@stevejburge what's the conclusion here? 

1.) Add admin notice and deactivate plugin using deactivate_plugins() 
2.) Add admin notice only.
3.) @agapetry if you're against using deactivate_plugins() to deactivate the free plugin, what other method do you propose, we should call all active plugins, remove the plugin from list and update options, isn't that what deactivate_plugins() does as well?

**Comment by agapetry** [comment]
@olatechpro I'm open to discussion on this. It will be good for the rest of the team to weigh in. With a widely distributed plugin running with every possible configuration, I just want to be careful about:

- introducing a pluggable function we've never used before
- executing it on every site access, front-end and admin

Even if we could mitigate one of those risk factors, I would be more comfortable with it.

**Comment by htmgarcia** [comment]
@andergmartins it seems Checklists already works this way. If you install and activate Pro, Free is deactivated.
May you point us to the involved code, please?

**Comment by andergmartins** [comment]
I do agree we need to define here the standard approach for all plugins we have, +1 for adding to the dev docs site. 

Whatever approach we decide here, I think we should pay attention on:

* Always warn users. Specially BEFORE doing anything related to plugin deactivation or data migration;
* Avoid potentially unnecessary file/dir reading proccess to reduce disk I/O usage;
* Use as less resources as possible to not hurt performance on busy sites;
* Reliability, or robbustness, not breaking the plugins/site if both/multiple plugins are activated;

----

Here are some points I would like to highlight (sorry for the long text):

## 1. Do not break sites

The ideal, is probably we should always make sure both Free and Pro plugins can be activated together without breaking the site or generating error/warning messages. They don't need to work together, but should not break anything. We can use `function_exists`, `defined` and `class_exists` before defining functions, constants or classes to avoid defining them twice.

The `class_exists` approach is probably not necessary if you are using an autoloader.

For making sure, we need to make tests focused on that before every release, checking if a site breaks if Free and Pro are both activated.

## 2. When to look for the Free plugin?

### Check constantly?

This is an option, but we need to be careful to use it, specially if we are reading dirs looking for the specific files.

I already received more than one report about high Disk I/O usage rates so I had to modify a little how the PublishPress plugin was doing that.

I'm not sure it makes sense to run a check on every request for something that might happen once, or just a few times in all the life-cicle of the site.

If we do that, we need to be sure we are not forcing directory reading looking for the correct files. At the same time, we can not guarantee all the sites have the plugins on the standard directory. I already found customers' sites where PublishPress was installed at `publishpress-1/publishpress.php` instead of `publishpress/publishpress.php`, just as an example.

Should we run that on the front-end? Cron tasks? Admin ajax? I don't think so... if we do that, it would probabaly be only on admin requests, in my opinion.

### On plugin activation

It might work only when the Pro plugin is installed after the Free plugin. If we have the invese scenary, we would only be able to catch that if the Free plugin is doing the check as well.

Using this approach we avoid a lot of checkings on every request, maybe saving some resources in the long term.

## 3. Should we deactivate the plugin?

I'm not sure we should take (or keep taking) that action, because disabling a plugin can activate other actions/filters for 3rd party plugins that we don't have control. And doing that without warning the user first, maybe we can cause some confusion or sense of loosing control?

We would need to include/require some functions (from `wp-admin/includes/plugin.php`) that are not loaded by default on the context of every request (maybe it is on plugin activation, but I'm not sure), as Kevin pointed out.

And once the admin is alware he should not run both plugin together we will probably not install them together again.

Maybe we could just make sure the plugins do not break the site if installed together, and rise a flag that says the plugin should enter on a `halt` mode until that flag is rised? For example, if I find a specif Free plugin's constant (that was not initialized by the Pro plugin), the Pro plugin will just stops its code initialization until it do not see that constant. 

Another point is that the Pro plugin carries the Free plugin inside it, so we need to be able to know if it was initialized by the Pro plugin or by itself.

## 3. How to check if Free, or duplicated plugin is activated?

We don't need to worry only if Free + Pro are activated, but if the same plugin is loaded twice. I saw that happening on a few customers' sites.

Maybe we could use simple `if (defined(PLUGIN_CONSTANT_HERE))` checks? It is a lot less resource consuming than a `file_exists` check.

## 4. Warn the user

I'm now a little worried about warning the use AFTER we take any action. Considering we are manipulating someone's site, I think we should always be sure to warn them before doing anything.

This is something I think we need to improve on Authors and PublishPress (maybe other plugins) avoiding to automatically migrate data when a plugin is activated. WP do not do that, WooCommerce to do not that, and probably other big plugins don't as well. What if anything goes wrong in the middle of the process of migrating or deactivating plugin? Do we corrupted any data? Was the user aware and prepared with a backup before doing anything?
What if the plugin was automatically updated?

I see WP and WooCommerce always asking me (after an update) to run the Data/DB update routine, which can be done asynchronously, when I want, or when I'm prepared for that. Is that required for the new update/plugin to work? Ok, let's warn the user and stop the plugin (only the plugin) until that is done, but when that is done, I think the user is the one to make that call.

**Comment by andergmartins** [comment]
Thanks @stevejburge that is a smart solution, we could implement something like that for new versions. But it won't detect legacy versions of the free plugin that don't run that action because it was not implemented there before.

**Comment by stevejburge** [comment]
One more idea here:
`
add_action( 'init', function(){ if function_exists('my_free_plugins_function'); deactivate_plugins( 'my_free_plugin');});`

**Comment by agapetry** [comment]
@stevejburge These points from @andergmartins stand out as reasons to "disable" a free plugin internally by skipping its normal execution, but not by formally deactivating it:

- disabling a plugin can activate other actions/filters for 3rd party plugins that we don't have control. And doing that without warning the user first, maybe we can cause some confusion or sense of loosing control?

- We would need to include/require some functions (from wp-admin/includes/plugin.php) that are not loaded by default on the context of every request

**Comment by agapetry** [comment]
@olatechpro Are you planning to implement the standard solution that @andergmartins is working on, or defer this to a later release?

**Comment by olatechpro** [comment]
Yes, this PR will remain pending till @andergmartins completed the sample solution @agapetry

**Comment by olatechpro** [comment]
@agapetry this PR has been updated using the https://github.com/publishpress/publishpress-instance-protection package.

**Pull request merged**
