### PR TITLE
feature/#745_Upgrade_PHP_support_to_7_2_minimum

### PR DESCRIPTION
**Pull request by olatechpro**
- Upgrade PHP support to 7.2 minimum #745

### CODE REVIEW

**Review by agapetry — COMMENTED** [review]
Good, but can this be abstracted to work for capabilities-pro/capabilities-pro.php (or whatever the plugin's own folder and filename are)?  Also note that the includes-core folder is intended for code that will not be loaded by Capabilities Pro

**Comment by olatechpro** [comment]
@agapetry I've moved the version check file to root folder so we can get plugin data as well support both free and pro version together.

Kindly check new update

**Review by agapetry — COMMENTED** [review]
Please check with @andergmartins on vendor library versions. His last guidance to me was:

> For pimple I would use: “^3.5"
> For psr/container, I would use: “2.0.0”

However, before applying that upgrade (or changing these library versions at all), I think we need to do more testing with various plugin combinations. Interactions with other plugins using the same library can cause unforeseen issues.

**Comment by olatechpro** [comment]
@agapetry I'll wait on this PR till the documentation on this is completed and concluded.

**Pull request closed without merging**
