### PR TITLE
feature/#4_Allow_people_to_target_CSS_to_user_roles 

### PR DESCRIPTION
**Pull request by olatechpro**
- Allow people to target CSS to user roles #4
- Frontend Features screen

### CODE REVIEW

**Comment by agapetry** [comment]
@olatechpro @stevejburge  Here's a UI consistency issue to decide on. Looking at Capabilities screen headlines, we currently have:

- Editor Feature Restriction  (and within the page, "Gutenberg Editor Post Restriction")
- Admin Feature Restrictions
- Admin Menu Restrictions
- Profile Features Restrictions

There are actually three variations here:
- No plural
- Plural "Restrictions"
- Double plural

The double plural definitely looks and sounds wrong (or at least awkward).  Technically, you could make a case for "Restriction" as the act of restricting, but "Restrictions" points more directly to the specific rules which have (or can be) defined.  So I think our screen headlines should be:

- Editor Feature Restrictions  (and within the page, "Gutenberg Editor: Post Restrictions")
- Admin Feature Restrictions
- Admin Menu Restrictions
- Profile Feature Restrictions

**Comment by stevejburge** [comment]
@agapetry good point. I agree with your final answer:


    Editor Feature Restrictions 
    Admin Feature Restrictions
    Admin Menu Restrictions
    Profile Feature Restrictions

**Comment by agapetry** [comment]
@olatechpro I'm still seeing this admin menu label when logged in as an Editor. I'll submit a fix for it tomorrow if you don't get to it first. 
image

**Comment by agapetry** [comment]
@olatechpro With the current PR, I'm having trouble hiding items with Frontend Features > Frontend Elements.

I've tried #adminbar and .site-title on my home page, which loads a single post. Also tried for a different single page. Currently testing the Editor role with the Twenty Twenty One theme. Is that an invalid use case? If so, we need some way for the admin screen to clarify theme limitations.

image

**Comment by olatechpro** [comment]
@agapetry I'm currently making changes to the UI, after I'm done, I'll notify you

**Comment by agapetry** [comment]
@olatechpro This shortens the menu caption when there is only one submenu item:

image

https://github.com/publishpress/PublishPress-Capabilities/pull/706/commits/4d0972e2738106160edea9485e680c1b83926b48

**Comment by olatechpro** [comment]
Got it @agapetry

**Comment by agapetry** [comment]
@olatechpro I'm not seeing any body class entries applied on the front end. Can you check that?  Tried for both whole site and selected pages:

image

.
Here's the resulting body tag:

image

**Comment by olatechpro** [comment]
You're right @agapetry I've made a commit to fix the issue

**Comment by agapetry** [comment]
@olatechpro This is the reason for https://github.com/publishpress/PublishPress-Capabilities/pull/706/commits/01062b03c8ba61b93ee99bb4dc609564cb17d181

Feel free to replace my width change with a different style rule to fix the right alignment:

image

**Comment by agapetry** [comment]
@olatechpro One more small thing, we need to fix the formatting of these links. They should look like the corresponding box in Authors:

image

image

**Review by agapetry — COMMENTED** [review]
Good work, @olatechpro

**Comment by olatechpro** [comment]
Thanks @agapetry

**Pull request merged**
