### PR TITLE
feature/#834_Access_to_Capabilities_Gone

### PR DESCRIPTION
**Pull request by olatechpro**
- Access to Capabilities Gone #834

### CODE REVIEW

**Review by agapetry — COMMENTED** [review]
@olatechpro Can you confirm my last commit still meets your requirements?

**Comment by olatechpro** [comment]
@agapetry Your commit is perfect, adding the check before the menu load surely fixes the issue mentioned.

**Comment by olatechpro** [comment]
Maybe we need to add extra check of `if (!current_user_can('manage_capabilities'))` so the function doesn't keep running everytime but only when admin lose the manage_capabilities? @agapetry

**Comment by olatechpro** [comment]
@agapetry Added the `if (!current_user_can('manage_capabilities')) `check

**Review by agapetry — APPROVED** [review]

**Pull request merged**
