### PR TITLE
feature/#531_Support_WordPress_API_for_Classic_Editor_disable_enable

### PR DESCRIPTION
**Pull request by olatechpro**
- Support WordPress API for Classic Editor disable / enable #531

### CODE REVIEW

**Review by agapetry — CHANGES_REQUESTED** [review]
@olatechpro pp_capabilities_is_classic_editor_available() should add more ways of detecting Classic Editor usage.  See how this Revisions function also looks at the "use_block_editor_for_post_type" and "use_block_editor_for_post" filters: https://github.com/publishpress/PublishPress-Revisions/blob/master/utils.php#L48.  This was derived from @andergmartins' work in PublishPress, and should probably become a library function at some point.

**Comment by olatechpro** [comment]
Okay @agapetry I'll update the pp_capabilities_is_classic_editor_available() method.

That aside, i don't know if you're implying the newly added settings will not really be needed after updating this method.

I couldn't really figure out if you have comment on the settings or not from your reply

@agapetry

**Comment by agapetry** [comment]
@olatechpro The manual enable switch is fine, but detecting this filter usage will save some users from that step of discovering and applying the switch.

**Comment by olatechpro** [comment]
@agapetry I've checked the linked https://github.com/publishpress/PublishPress-Revisions/blob/master/utils.php#L48 to see what can is useful in the method to detect classic editor for our usage but find now.

Currently, we're checking the following condition:
```
class_exists('Classic_Editor')
        || function_exists( 'the_gutenberg_project' )
        || class_exists('Gutenberg_Ramp')
        || version_compare($wp_version, '5.0', '<')
        || class_exists('WooCommerce')
        || (defined('PP_CAPABILITIES_CONFIGURE_CLASSIC_EDITOR') && PP_CAPABILITIES_CONFIGURE_CLASSIC_EDITOR)
        || !empty(get_option('cme_editor_features_classic_editor_tab'))
        || (function_exists('et_get_option') && 'on' === et_get_option('et_enable_classic_editor', 'off'));
```

You should note, the function `pp_capabilities_is_classic_editor_available()` is currently been used on editor features page and not on post editor screen. So, the $_REQUEST editor check may not apply and also the `use_block_editor_for_post_type` filter is useless on the screen as well to determine if block editor is disabled as it's capability editor features page and not post type editor screen and the `isBlockEditorActive()` seems to be targetted on post editor.

I'm ready to add any use case as they come but right now, i've checked and can't find any known condition that's missing from the conditions above but if there's any i'm missing, you can point me to the right direction

**Comment by agapetry** [comment]
@olatechpro I see what you mean. The missing piece is the "use_block_editor_for_post_type" and "use_block_editor_for_post" filters, which themes sometimes hook into.  You're right that those can't be tested on the Capabilities screen.  Maybe we should just include a short note about this (or even a "show Classic Editor controls" button) at the bottom of the Editor Features screen.

**Comment by olatechpro** [comment]
@agapetry  I added a "show Classic Editor controls" button at the bottom of the Editor Features screen as suggested but the button only show if classic editor check method return false else, the button will never come up while still leaving the on and off control the way it is in settings.

The reason for making the button one way is because it's more logical since the classic editor control may show due to other condition and as a result, i don't think introducing a "hide Classic Editor controls" is ideal as this only update option which is one of many conditions from showing the tab.

**Comment by agapetry** [comment]
Nicely done, @olatechpro. I have only one more issue that should be easy to address.  When Capabilities > Settings is first accessed (and after settings update), the screen defaults to the Role tab, but that tab does not have "selected" styling:

image

**Comment by olatechpro** [comment]
I've added active class to default tab. @agapetry

**Review by agapetry — APPROVED** [review]

**Pull request merged**
