### PR TITLE
feature/#578_Adding_an_explanation_for_Checkmark_empty_X

### PR DESCRIPTION
**Pull request by olatechpro**
- Adding an explanation for Checkmark / empty / X #578

### CODE REVIEW

**Review by agapetry — COMMENTED** [review]
I think it would make more sense to move the "changes remain in the database" text to the "Capabilities is safe" box. What do you think, @stevejburge? 

Some clarifications to the checkbox key are also needed:

- Empty checkbox doesn't mean "no changes". It means the capability is not granted by this role.
- X icon doesn't mean "not granted". It means the capability is negated (revoked). So if the user has another role with the same capability assigned, this red X overrides the other role.

Here's one way to string it all together more concisely:

image

Note that the proposed change also removes some excess padding and margin from the ul and replaces the literal bullet characters with a disc list style. I can submit a PR for this if you'd like.

But I also think the checkbox key would be more effective if it had a visual representation of the checked box, empty box and X icon instead of just naming them.

**Comment by olatechpro** [comment]
@agapetry I've made the update.

Note, changes was made to the css too.

**Comment by agapetry** [comment]
@olatechpro I've committed a few more refinements to this PR. Here are screen captures of the result. If you prefer to modify the markup to achieve this same Usage Key alignment without using a table, go ahead:

image

**Comment by agapetry** [comment]
@stevejburge @olatechpro Here's the Admin Features screen layout with my last commits:

.
.
**=== Admin Features (desktop view): ===**

image

.
.
**=== Admin Features (mobile view): ===**

image

...

image

**Comment by agapetry** [comment]
@stevejburge @olatechpro One more set of screen captures: Editor Features with my last commits:

.
.
**=== Editor Features (desktop view): ===**

image

.
.
**=== Editor Features (mobile view): ===**

image

...

image

**Comment by stevejburge** [comment]
Thanks @olatechpro @agapetry I think this feature will be very helpful

**Review by agapetry — APPROVED** [review]
Approved with my additional commits. @olatechpro, let me know if you have any concerns about my changes.

**Pull request merged**
