### PR TITLE
Ppc 22

### PR DESCRIPTION
**Pull request by htmgarcia**
#22
@stevejburge generated result:
Screen Shot 2021-11-09 at 12 48 21
Screen Shot 2021-11-09 at 12 47 58
Screen Shot 2021-11-09 at 12 47 24

### CODE REVIEW

**Comment by agapetry** [comment]
@htmgarcia Nice work, but we need to tweak that JS to make a re-selection of "Filter by post type" have the same effect as the Clear button.  Otherwise the checkbox array can be reduced to nothing:

image

**Comment by htmgarcia** [comment]
@agapetry 

> Otherwise the checkbox array can be reduced to nothing

How may I reproduce this scenario?

**Comment by agapetry** [comment]
@htmgarcia 

1. Select a post type in the filter dropdown
2. Return dropdown to default item "Filter by post type"

**Comment by htmgarcia** [comment]
@agapetry good catch! I commited a fix.

**Pull request merged**
