### PR TITLE
feature/#710_Nav_Menus_Block_Navigation/FSE_theme_support

### PR DESCRIPTION
**Pull request by olatechpro**
- Nav Menus Block Navigation/FSE theme support #710

### CODE REVIEW

**Review by agapetry — COMMENTED** [review]
Looks good once you clear up the notices I mentioned: https://github.com/publishpress/PublishPress-Capabilities/issues/710

**Comment by olatechpro** [comment]
@agapetry I've fixed the notice now. Kindly check

**Comment by agapetry** [comment]
@olatechpro I see that you fixed a different issue (parsing of nested blocks), but I still see the same notices from lines 557 to 560.

**Comment by agapetry** [comment]
@olatechpro Another issue: Nested nav blocks are displayed with a checkbox and the correct nesting level dash, but no title: 
image

**Comment by olatechpro** [comment]
@agapetry I finally see the issue with warning which happen with custom menu items and I'be made update to fix that as well include all menu depths.

Can you test again and confirm if all mentioned issues is gone?

**Comment by agapetry** [comment]
@olatechpro I can confirm that nested child blocks are now labeled correctly.

Some of the notices are gone, but lines 556 to 558 of functions.php still trigger notices for indexes "label", "url", "kind" :

image

**Comment by agapetry** [comment]
Also, note that a Navigation Block of type "Page List" is still not labeled correctly:

image

**Comment by olatechpro** [comment]
@agapetry I think the issue is related to the menu type.

How can i add the menu to produce this issue?

Currently, I can add menu from existing page or custom link

**Comment by agapetry** [comment]
@olatechpro Try adding a "Page List" or "Social Icons" item to the Navigation block: 
image
.
.
Currently, those each show up on our Nav Menus admin screen as an uncaptioned checkbox:
image

**Comment by olatechpro** [comment]
Thanks @agapetry I see what the issue now.

I'll start discussion on it on slack

**Comment by olatechpro** [comment]
@agapetry Can you test now?

I've added support for the following blocks 
- Site Logo, 
- Site Title, 
- Social Links, 
- Page Lists, 
- Search, 
- Home Link

**Comment by agapetry** [comment]
@olatechpro Nice, I can confirm this is generally working. I do still see two issues and one possible issue:

1. If a page is present in more than one menu location (for example, both directly placed as a Page Link and also present in a Page List), you sometimes have to toggle its checkbox in both locations for the desired configuration to be saved. That's sure to confuse and frustrate somebody.
2. A custom link URL restriction (checkbox selection) is not save if its label includes http://

The possible issue to consider is that selecting a Page List causes each page in the list to be presented as a separate checkbox on our config screen.  That's very versatile, but potentially overwhelming. I wonder if we need to support a "collapse" button like the Nav Block side panel has in Gutenberg editor: 
image

4. 
5.

**Comment by stevejburge** [comment]
Thanks for the careful review @agapetry 

Yes, 1 and 2 sound like issues we need to resolve.

I wonder if it's safest to not support "Page List" for now?

**Comment by agapetry** [comment]
I can confirm the checkbox sync and custom link updating issues are resolved.

**Comment by olatechpro** [comment]
Yea, those issues are fixed but to have collapsible buttons for the nav lists like the nav block side panel has in Gutenberg editor, I'll need more time to work that out as there's need for change of implementation judging based on our current implementation and structure making this week release not so sure again.

@stevejburge @agapetry

**Comment by stevejburge** [comment]
Thanks @olatechpro. Releasing next week is no problem at all

**Comment by olatechpro** [comment]
@agapetry This PR is now updated with collapsible menu support and you can test now

**Comment by agapetry** [comment]
@olatechpro The menu collapse works nicely. 

I see a bug in the front end implementation, though.  I'm not sure if this is new or previously unnoticed, but if I restrict a Navigation block item that has submenu items, the wp-block-navigation-submenu__toggle button is displayed as an orphan with nothing to toggle:

image
.
.
.
image

**Comment by agapetry** [comment]
@olatechpro Also noticed that when a page is restricted, its menu space is still displayed, due to the remaining list item. This will need to be fixed:

image
.
.
.
image

**Comment by olatechpro** [comment]
@agapetry I've changed method of application and restriction to remove item before they're rendered instead of relying only on css/js solution.

So, you can retest now

**Comment by agapetry** [comment]
@olatechpro Nice work on the menu item suppression.

I did find one last loose thread for you to tie off. In my test with the Author role, selected Page Link items are correctly suppressed from the Navigation block, but those hidden pages are not blocked if accessed by direct URL.

**Comment by olatechpro** [comment]
@agapetry  I can't understand why the pages are not been restricted for you. I just tested again and access to the pages are blocked for the users.

Maybe you should check again or provide ways you're testing for me to check

**Comment by agapetry** [comment]
@olatechpro Sorry, after updating the Navigation block, the pages are blocked correctly. There were no changes to the page link in question; I just added an another page link before updating the Nav block.

**Review by agapetry — APPROVED** [review]
@olatechpro Thanks for your diligence in following through on all the feedback.

**Comment by olatechpro** [comment]
Thanks @agapetry

**Pull request merged**
