### PR TITLE
feature/#580_Plugin_translation_ignores_users_language_setting

### PR DESCRIPTION
**Pull request by olatechpro**
- Plugin translation ignores user's language setting #580

### CODE REVIEW

**Review by agapetry — CHANGES_REQUESTED** [review]
@olatechpro With site language set to German and user language to English, my Capabilities link is still in German:

image

**Comment by olatechpro** [comment]
@agapetry I believe you may be testing with an incomplete or incorrect changes. 

Just tested on another site and it's working.

**Comment by olatechpro** [comment]
@agapetry I believe you may be testing with an incomplete or incorrect changes. 

Just tested on another site and it's working.

Here's the build package:

[capability-manager-enhanced.zip](https://github.com/publishpress/PublishPress-Capabilities/files/9744328/capability-manager-enhanced.zip)

**Review by agapetry — APPROVED** [review]
@olatechpro You're right, I overlooked the change in the main plugin file because the changes there are normally just version number. Sorry about the false alarm.

**Pull request merged**
