### PR TITLE
feature/9-block-access-to-admin-menu-links

### PR DESCRIPTION
**Pull request by olatechpro**
Screenshot 2020-10-06 at 12 11 33
Screenshot 2020-10-06 at 12 11 58
Screenshot 2020-10-06 at 12 26 04

### CODE REVIEW

**Comment by olatechpro** [comment]
@stevejburge , please link the issue and reviewer

**Comment by stevejburge** [comment]
Awesome, thanks @olatechpro

**Comment by agapetry** [comment]
@olatechpro The code is looking good overall.  I haven't tested functionality yet; just reviewing for some coding standards.  Let's use short syntax when creating arrays:

$my_new_array = [];

**Comment by olatechpro** [comment]
Hi @agapetry , i just updated the remaining array to short syntax as suggested and tested the code from this end to be sure everything is working fine. Kindly keep me updated when you review the features

**Pull request merged**
