### PR TITLE
Banner getting people to install Permissions

### PR DESCRIPTION
**Pull request by htmgarcia**
#201

Generated result: Permissions is now listed as first.
Screen Shot 2021-11-05 at 14 13 51

### CODE REVIEW

**Comment by htmgarcia** [comment]
Updated search term:
Screen Shot 2021-11-08 at 16 30 08

**Comment by htmgarcia** [comment]
Updated banner style:
Screen Shot 2021-11-08 at 16 31 06

**Comment by htmgarcia** [comment]
@agapetry I created a second PR that solves the same issue but uses vendor library: https://github.com/publishpress/PublishPress-Capabilities/pull/250 - The decision of which PR to merge, beyond the code quality, may require some discussion.

@stevejburge which other banners we may implement and in which plugins?

**Comment by stevejburge** [comment]
@htmgarcia Let's start with these:
- Inside Revisions, a sidebar banner telling people to install Capabilities to control who can create revisions
- Inside Authors, a sidebar banner telling people to install Blocks for blocks that integrate with Authors

**Comment by htmgarcia** [comment]
@stevejburge sounds good! This made me think the vendor library will be useful here. Just need to wait if @agapetry is ok with that approach.

**Pull request closed without merging**
