### PR TITLE
feature/#727_Custom_capabilities_for_each_feature

### PR DESCRIPTION
**Pull request by olatechpro**
- Custom capabilities for each feature #727

### CODE REVIEW

**Comment by agapetry** [comment]
@olatechpro After a user's role capabilities for this plugin are reduced to only "manage_capabilities", any  wp-admin access by them causes these PHP Notices:

image

**Comment by agapetry** [comment]
@olatechpro Reducing the role's plugin capabilities to only "manage_capabilities" also caused a duplicate admin menu item:

image

**Comment by agapetry** [comment]
@olatechpro Navigation Menu Restrictions seems to be missing some CSS if the user accesses it without also having manage_capabilities_admin_menus:

image

**Comment by agapetry** [comment]
@olatechpro This notice occurs on every wp-admin access if the user has plugin capabilities assigned only with negation:

image

image

**Comment by olatechpro** [comment]
@agapetry 
Thanks for taking your time to test this carefully,

I've worked on all the warning error notices and you can retest now.

There're still two issues I'll need your comment on how to go about it.

1. The reason I'm adding the title to a single menu is because when a menu is added via add_menu_page() and has only one submenu which is same as the menu, WordPress doesn't add the submenu unless the menu has more than 1 sub menu. So, What other way do you think this could be achieve?
2. 
3. For the Test User additional capabilities, I noticed you added more note to the feature Dashboard description. Will that be enough or this should be added somewhere else?

**Comment by agapetry** [comment]
@olatechpro 

> The reason I'm adding the title to a single menu is because when a menu is added via add_menu_page() and has only one submenu which is same as the menu, WordPress doesn't add the submenu unless the menu has more than 1 sub menu. So, What other way do you think this could be achieve?

I see your reason, but wonder if the Capabilities > Dashboard behavior points to a solution. The Upgrade to Pro item is a second menu item.  Is there a difference in the add_submenu_item() execution timing that causes WP to recognize it and render the submenu items?

Another angle would be to add the Dashboard submenu whenever any other submenus are due, but show the feature settings as "read only" if the user lacks the manage_capabilities_dashboard capability. That would also resolve the menu handling for Pro, where there is no Upgrade submenu item.

**Comment by agapetry** [comment]
> For the Test User additional capabilities, I noticed you added more note to the feature Dashboard description. Will that be enough or this should be added somewhere else?

In my opinion, a many users won't bother reading the description even if they go to the Dashboard page. So I think a short note next to the manage_capabilities_user_testing checkbox would be helpful and simple to implement.

**Comment by olatechpro** [comment]
@agapetry I've updated the Test user capability message

**Pull request merged**
